// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "wmperroritem.h"


/////////////////////////////////////////////////////////////////////////////
// CWMPErrorItem properties

/////////////////////////////////////////////////////////////////////////////
// CWMPErrorItem operations

long CWMPErrorItem::GetErrorCode()
{
	long result;
	InvokeHelper(0x385, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString CWMPErrorItem::GetErrorDescription()
{
	CString result;
	InvokeHelper(0x386, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

VARIANT CWMPErrorItem::GetErrorContext()
{
	VARIANT result;
	InvokeHelper(0x387, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

long CWMPErrorItem::GetRemedy()
{
	long result;
	InvokeHelper(0x388, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString CWMPErrorItem::GetCustomUrl()
{
	CString result;
	InvokeHelper(0x389, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}
