// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "wmpplaylistarray.h"

// Dispatch interfaces referenced by this interface
#include "wmpplaylist.h"


/////////////////////////////////////////////////////////////////////////////
// CWMPPlaylistArray properties

/////////////////////////////////////////////////////////////////////////////
// CWMPPlaylistArray operations

long CWMPPlaylistArray::GetCount()
{
	long result;
	InvokeHelper(0x1f5, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CWMPPlaylist CWMPPlaylistArray::Item(long lIndex)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1f6, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		lIndex);
	return CWMPPlaylist(pDispatch);
}
