#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(dirname);

sub __DIR__ {
	return dirname +(caller 0)[1];
}

# this must go before use Pod::Html to use our private copy
use lib __DIR__ . '/lib';
use Pod::Html;

chdir( __DIR__ ) or die $!;
pod2html(
#	"pod2html",
	"--header",
	"--infile=lib/Xchat.pod",
	"--outfile=xchat2-perl.html",
);

#system( qw(tidy -m -i -xml -utf8 -quiet xchat2-perl.html) );
unlink( "pod2htmd.tmp" );
unlink( "pod2htmi.tmp" );

exec( "./syntax_highlight", "xchat2-perl.html" )
	or die $!;
